CREATE TABLE IF NOT EXISTS projects (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  priority integer NOT NULL,
  description text,
  deliverydate date NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  login text NOT NULL CHECK (name <> ''),
  profession text NOT NULL CHECK (profession <> ''),
  projectid INTEGER REFERENCES projects(id)
);

------- INSERT projects DATA------
INSERT INTO projects(name, priority,description,deliverydate)
 VALUES('emerginov','1','web application','2020-01-01');
INSERT INTO projects(name, priority,description,deliverydate)
  VALUES('emerginov II','1','web application','2021-01-01');
INSERT INTO projects(name, priority,description,deliverydate)
   VALUES('emerginov III','1','web application','2022-01-01');

------- INSERT users DATA--------
INSERT INTO users(name, profession,projectid,login)
 VALUES('moncef','student','2','b');
 INSERT INTO users(name, profession,projectid,login)
  VALUES('nicolas','student','2','a');
